name: Build and Release Process

# Defines environmental variables
env:
  GO_VERSION: '1.22.2'

on:
  release:
    types: [ published ]

jobs:
  build_and_upload_ubuntu:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # v4.2.1

    # Setup Go
    - name: Setup Go
      uses: actions/setup-go@0a12ed9d6a96ab950c8f026ed9f722fe0da7ef32 # v5.0.2
      with:
        go-version: "${{ env.GO_VERSION }}"

    - name: Build and Run
      run: |
        go build -o festerize main.go

    # Zip binary for Ubuntu
    - name: Zip binary
      run: zip festerize_ubuntu.zip festerize

    - name: Upload Ubunutu Release Assets
      uses: softprops/action-gh-release@c062e08bd532815e2082a85e87e3ef29c3e6d191 # v2.0.8
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        files: festerize_ubuntu.zip

  build_and_upload_mac:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # v4.2.1

    # Setup Go
    - name: Setup Go
      uses: actions/setup-go@0a12ed9d6a96ab950c8f026ed9f722fe0da7ef32 # v5.0.2
      with:
        go-version: "${{ env.GO_VERSION }}"

    - name: Build and Run
      run: |
        go build -o festerize main.go

    # Zip binary for Mac
    - name: Zip binary
      run: zip festerize_mac.zip festerize
    - name: Upload Mac Release Assets
      uses: softprops/action-gh-release@c062e08bd532815e2082a85e87e3ef29c3e6d191 # v2.0.8
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        files: festerize_mac.zip

  build_and_upload_mac_intel:
    runs-on: macos-12

    steps:
    - uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # v4.2.1

    # Setup Go
    - name: Setup Go
      uses: actions/setup-go@0a12ed9d6a96ab950c8f026ed9f722fe0da7ef32 # v5.0.2
      with:
        go-version: "${{ env.GO_VERSION }}"

    - name: Build and Run
      run: |
        go build -o festerize main.go

    # Zip binary for Mac
    - name: Zip binary
      run: zip festerize_mac_intel.zip festerize
    - name: Upload Mac Release Assets
      uses: softprops/action-gh-release@c062e08bd532815e2082a85e87e3ef29c3e6d191 # v2.0.8
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        files: festerize_mac_intel.zip

  build_and_upload_windows:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # v4.2.1

    # Setup Go
    - name: Setup Go
      uses: actions/setup-go@0a12ed9d6a96ab950c8f026ed9f722fe0da7ef32 # v5.0.2
      with:
        go-version: "${{ env.GO_VERSION }}"

    - name: Build and Run
      run: |
        go build -o festerize main.go

    # Zip binary for Windoes
    - name: Zip binary
      run: Compress-Archive -Path festerize -DestinationPath festerize_windows.zip
    - name: Upload Window Release Assets
      uses: softprops/action-gh-release@c062e08bd532815e2082a85e87e3ef29c3e6d191 # v2.0.8
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        files: festerize_windows.zip
